plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mehdi.hava'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mehdi.hava'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
